[package]
name = "burette"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = [ "derive" ] }
file-format = "0.26.0"
serde = { version = "1.0.217", features= [ "derive" ] }
serde_json = "1.0.137"
sha2 = "0.10.8"
